### ISSUE TITLE
create and upload war file

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#10]
pls create and upload a war file on regular basis for further tests by the community

**Comment by hylkevds** [comment]
Maybe you are already familiar with the GitHub build system, or the Travis build system, but it's not hard to automatically build the war file every commit, and deploy or upload it.

**Comment by kgaeb** [comment]
@hylkevds:
we decided, that the war file will be created and pushed here, as soon as the part of the server side config is available at a minimum (coming soon) - this would then allow to play with the build also locally - but thanks for the hint anyway!

**Comment by kgaeb** [comment]
see #18
