### ISSUE TITLE
SQLite DB - refresh doesn't work

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#113]
existing behavior:
when adding any file to the sqlite directory for the ogcapisimple which is not a sqlite file, then api doesn't scan the directory again

expected behavior:
when adding any file to the sqlite directory for the ogcapisimple which is not a sqlite file, then api shall scan the directory again.  And check if the new file is a sqlite DB which can be shown in the application.

**Comment by kgaeb** [comment]
the test is as follows:
1) place any file which is not a sqlite file into the sqlite directory
2) ogcapisimple throws an error in the log and does nothing (that's working ok)
3) place a valid sqlite file in the sqlite directory (now the ogcapisimple doesn't do anything, at least in the logs)

Expected behavior would be:
Whenever a valid sqlite file is placed in the directory the ogcapisimple should rescan the directory and show the sqlite file in the connections and in the dashboard.

Is that clear enough?

**Comment by TobiasPressler** [comment]
The problem was coused by an exception that was thrown in the onCreate callback of the filesystem change listener. This stopped the watcher.
