### ISSUE TITLE
Composite PK on tables is not honoured

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#117]
The question came up, because from table insp_navaid the attribute navaidtypevalue is shown as possible Id and to my understanding this should not be the case.

**Comment by TobiasPressler** [comment]
Currently the server checks for all column with an unique constrain.

**Comment by kgaeb** [comment]
the table tna.insp_navaids has the following index:
CREATE UNIQUE INDEX insp_navaids_pkey ON tna.insp_navaids USING btree (navaid_pk, navaidtypevalue)
with the constraint:
PRIMARY KEY (navaid_pk, navaidtypevalue)
This means, the table has a PK consisting of both columns.
Any suggestion how we could handle such situations?

**Comment by TobiasPressler** [comment]
How does the Geo server handle such situations?

**Comment by hylkevds** [comment]
I suppose the core of the problem with composite PKs is that OGC API - Features assumes that the identifier of a feature is a single variable.
The pragmatic solutions would be to either:

- Disallow tables that do not have a unique column of a suitable data type that can be used as key.
- Allow composite PKs, and handle that in the API by concatenating the PK parts to generate the feature id. Preferably with a separator, so that it is possible to separate the parts again when fetching a feature by id. Would need a check to ensure the separator does not appear in the values of any of the PK columns.

**Comment by kgaeb** [comment]
after our discussion today we will implement in the backend the following solution:
a table/collection is shown in the frontend only, if the table holds at least one column
1) which is either a primary key column (single column only, no composite PK) or
2) which is defined as being unique.
Tables which are not conforming to this requirement are not shown in the backend and an entry in the log is generated (suggestion: as a warning).
This behaviour should be valid for PostgreSQL AND SQLite tables, but should not be applied to SQL Views defined in the Dashboard. We assume the user responsible to create an appropriate PK/ID for SQL defined collections. With this solution the user is able to create an SQL collection with tables from PostgreSQL and SQLite which are not shown in the Dashboard due to a missing PK/unique column.

**Comment by kgaeb** [comment]
this is not fixed - e.g. the table insp_navaids has:
1) a unique index on 2 (!!) columns and not one [CREATE UNIQUE INDEX insp_navaids_pkey ON tna.insp_navaids USING btree (navaid_pk, navaidtypevalue)]
2) a primary key consisting of 2 (!!) columns and not one [PRIMARY KEY (navaid_pk, navaidtypevalue)]
According to my previous comment, this table should not be shown in the list of tables. Instead it should be shown in the logs as warning.

**Comment by kgaeb** [comment]
This works now for the PostgreSQL table insp_navaids. But the entry in the log is still missing.
Tested with the following SQL statement from a PostgreSQL table:
select navaid_pk || '-*-' || navaidtypevalue as primkey, navaidtypevalue, designator, geogname, geom from tna.insp_navaids

Works also for SQLite DB, but there is no entry in the log, that the tables do not have a PK/Unique Field!
Tested with the following SQL statement from a SQLLite table:
select * from tna_insp_airspacearea
