### ISSUE TITLE
BBOX in API not working

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#118]
bbox=(8,46,14,51) should cover approx. the western half of Austria

1. http://localhost:8086/ogcapisimple/collections/Navaids/items?bbox=(8,46,14,51)
--> bug, bbox not working, returns all records in html, should be json

2. http://localhost:8086/ogcapisimple/collections/Navaids/items?bbox=(8,46,14,51)&f=application/json
--> bug, bbox not working, returns all records in html, should be json

3. http://localhost:8086/ogcapisimple/collections/Navaids/items?bbox=(8,46,14,51)&f=text/html
--> bug, bbox not working, returns all records, html is ok here

**Comment by TobiasPressler** [comment]
Referent to http://docs.opengeospatial.org/DRAFTS/17-069r1.html#_parameter_bbox The bbox array should be inputed without braces. For example: bbox=1,2,3,4.

**Comment by kgaeb** [comment]
Thanks for the hint for the bbox format - the correct link would be to the released document instead (http://docs.opengeospatial.org/**is**/17-069r3/17-069r3.html)
