### ISSUE TITLE
Properties request not working in API

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#119]
1) http://localhost:8086/ogcapisimple/collections/Navaids/items?designator=GSB
this is ok, delivers json (single feature)

2) http://localhost:8086/ogcapisimple/collections/Navaids/items?designator=GSB&f=text%2Fhtml
--> bug, delivers all records, html is ok here

3) http://localhost:8086/ogcapisimple/collections/Navaids/items?designator=GSB&f=text/html
--> bug, delivers all records, html is ok here

4) http://localhost:8086/ogcapisimple/collections/Navaids/items?designator=GSB&f=application/json
--> bug, delivers nothing, not even an error

5) http://localhost:8086/ogcapisimple/collections/Navaids/items?navaidtypevalue=DME
--> ok, delivers json (7 features)

6) http://localhost:8086/ogcapisimple/collections/Navaids/items?navaidtypevalue=DME&designator=KOR
--> ok, delivers json (one feature)

7) http://localhost:8086/ogcapisimple/collections/Navaids/items?navaidtypevalue=ILS_DME&designator=OEG
--> bug, delivers nothing, should deliver 3 records

8) http://localhost:8086/ogcapisimple/collections/Navaids/items?navaidtypevalue=*DME
--> bug, delivers nothing, see spec 7.15.5. Parameters for filtering on feature properties
in my opinion this should deliver all records with "*DME" in the property navaidtypevalue - but we can discuss, if this is correct.

9) http://localhost:8086/ogcapisimple/collections/Navaids/items?designator=G*
--> bug, delivers nothing, see spec 7.15.5. Parameters for filtering on feature properties
this request should deliver 4 records, all navaids with the designator starting with "G"

**Comment by TobiasPressler** [comment]
Filters fixes, html is ignoring all filters. #132
