### ISSUE TITLE
icons for Id and geometry missing in SQL collections

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#130]
The icons for possible Id columns/properties and the geometry column is not shown. Please add them for the SQL Views/collections as well.

**Comment by LukasGaebler** [comment]
In the backend it is not possible to check if views have columns which would suit as id or geo column.
My suggestion would be that the icons are shown if a column is selected as geo or id column. But as it is not possible to check if a column is suitable for one of these categories all of the columns could be selected as geo or id column

**Comment by kgaeb** [comment]
Agreed: It is up to the user to decide which columns are a geometry / id column!
