### ISSUE TITLE
Add option for setting Cross Origin Resource Sharing (CORS) headers

### ISSUE THREAD

**Issue by hylkevds** [DataCoveEU/API4INSPIRE#140]
One of the main use-cases for the API is web applications that display data from various sources. For this to work, those source servers must allow Cross Origin Resource Sharing (CORS) by setting the relevant headers.
For details on CORS, see https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

Please add a way to enable/disable CORS, and configuring the contents of the relevant headers.

**Comment by kgaeb** [comment]
@hylkevds 
in my opinion CORS relevant headers should be set as close as possible to the client (would mean a proxy server before Tomcat (which is not part of the dev works) or in Tomcat itself (would be in the Dockerfile, but I wouldn't like that very much).
@all:
I would be glad to know your opinions on that.

**Comment by TobiasPressler** [comment]
By adding a CORS Filter to the Tomcat web.xml config, Tomcat would be able to set the headers correctly. For example: `<filter>
    <filter-name>CorsFilter</filter-name>
    <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
</filter>
<filter-mapping>
    <filter-name>CorsFilter</filter-name>
    <url-pattern> /* </url-pattern>
</filter-mapping>`

**Comment by kgaeb** [comment]
during our discussion we decided, that the CORS headers will be not implemented in the backend software. Instead we will document (only) the configuration for the Tomcat installation within the docker container.
This provides flexibility to the user to implement the required CORS header either in the Tomcat of the docker container or in a proxy server under the responsibility of the user.
see: https://github.com/DataCoveEU/API4INSPIRE/blob/master/OGCAPISimple/docs/docker_postgis_inspire.md#apache-tomcat-cors-handling
