### ISSUE TITLE
SQL: unexpected behaviour for buttons "Execute", "Update" and "Delete" 

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#147]
"Execute" - existing behaviour:
When an existing SQL table/collection is selected and the collection name is changed, without changing anything in the SQL the click on the "Execute" button shows an error "null". A second click on the "Execute" button adds the new collection to the list

"Execute" - expected behaviour:
When an existing SQL table/collection is selected and the collection name is changed, without changing anything in the SQL the first click on the "Execute" button should add the new collection to the list
-----------------------------------------------
"Update" - existing behaviour:
When an existing SQL table/collection is selected and the collection name is changed, the "Update" button does something, but the result is not reflected in the list of tables / collections. When the Dashboard is left and loaded new, the updated SQL table / collection doesn't hold an SQL statement and the changed name is not honoured

"Update" - expected behaviour:
When an existing SQL table/collection is selected and the collection name is changed, the "Update" button should update the SQL collection name and the result is should be shown in the list of tables / collections. The SQL statement should be shown as well and should not be lost!
-----------------------------------------------
"Delete" - existing behaviour:
When an existing SQL table/collection is selected and the collection is deleted, a selection of another SQL collection in the list doesn't show the SQL and collection name anymore. Only when the Dashboard is left and reloaded the SQL and collection name is shown.

"Delete" - expected behaviour:
When an existing SQL table/collection is selected and the collection is deleted, a selection of another SQL collection in the list should show the SQL and collection name.

**Comment by kgaeb** [comment]
"Execute" - existing behaviour:
When an existing SQL table/collection is selected and the collection name is changed, without changing anything in the SQL the click on the "Execute" button shows the red text "A sql query is required". Changing the SQL and a click on the "Execute" button performs the addition of the SQL as new table.
"Execute" - expected behaviour:
When an existing SQL table/collection is selected and the collection name is changed, without changing anything in the SQL the click on the "Execute" button should add the SQL as new table/collection.
The program deletes the ";" at the end of the SQL - please check if this is the problem.

"Update" - existing behaviour:
When an existing SQL table/collection is selected and the collection name is changed, the "Update" button changes the name and the result is reflected in the list of tables / collections. When clicking on the entry in the collection list the updated SQL table / collection doesn't hold an SQL statement. The collection is empty!
"Update" - expected behaviour:
When an existing SQL table/collection is selected and the collection name is changed, the "Update" button should update the SQL collection name and the result is should be shown in the list of tables / collections. The SQL statement should be shown as well and should not be lost!

"Delete" - existing behaviour:
When an existing SQL table/collection is selected and the collection is deleted, a selection of another SQL collection in the list doesn't show the SQL and collection name anymore. Only when the Dashboard is left and reloaded the SQL and collection name is shown.

"Delete" - expected behaviour:
When an existing SQL table/collection is selected and the collection is deleted, a selection of another SQL collection in the list should show the SQL and collection name.

**Comment by LukasGaebler** [comment]
When deleting an existing SQL table/collection, why should any other be selected? And which one should be selected and what should be selected if this was the only existing SQL table/collection?

**Comment by kgaeb** [comment]
Update still not working correctly - pls try yourself.

**Comment by kgaeb** [comment]
additional:
1) the selected row in the tables is wrong after the execute button is pressed
2) after an update of the table/collection no row in the table list is selected --> the updated records should be selected; also no further row can be selected anymore

**Comment by kgaeb** [comment]
still open

**Comment by kgaeb** [comment]
Yes!! Fixed!
