### ISSUE TITLE
Autogenerate Docker image

### ISSUE THREAD

**Issue by hylkevds** [DataCoveEU/API4INSPIRE#18]
It would be great if you could set up an auto build for docker images. That would make deploying the latest version super easy.

**Comment by kgaeb** [comment]
Docker container is ready, Lukas and Tobias are working on the automated WAR file generation when a pull request is done.
The directory for the ogcapisimple.war file will be here: "API4INSPIRE/docker/ogcapisimple". This allows cloning/pulling the repo and creation of the image as described in /docs/docker_postgis_inspire.md

**Comment by kgaeb** [comment]
Done - Dockerfile including installation of the application within a Tomcat ready. 
see [/docs/docker_postgis_inspire.md](https://github.com/DataCoveEU/API4INSPIRE/blob/master/docs/docker_postgis_inspire.md)
