### ISSUE TITLE
directory for logs

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#31]
the directory/file "../ogcapisimple/logs" during deployment of the app in tomcat doesn´t exist and the deployment process fails.
2 possibilities:
1) create the directory in the war file, in order to have it available at the time of deployment
or
2) have a config file, where the path for the log files can be set by the administrator

2nd option is preferred, in order to be able to inject the config file from outside into the docker container and to create the possibility to use a directory for the logs outside of the app (important for automated log server and log observation).

**Comment by TobiasPressler** [comment]
The log path will be editable through the web interface (has to be implemented by @LukasGaebler ), but if environment variable log4j.saveDirectory is set, the given path will be used.
