### ISSUE TITLE
ENV variable to configure hostname

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#75]
pls create the possibillity to use an ENV variable for the hostname.
this variable should be used in the back-/frontend if required and would give the possibility to use the app behind a proxy

**Comment by TobiasPressler** [comment]
In the latest version, the Host header is used. This ensures that always the hostname, the request came from, is used in the links, even behind a proxy. Should it be changed anyway?

**Comment by kgaeb** [comment]
Kindly ask you to implement an ENV variable anyway. If not set, then the software should use the host header as it is now. Thanks!

**Comment by hylkevds** [comment]
The reason for the request is that the host header is probably not correct for requests that pass through a reverse proxy. In this situation, the externally reachable host is the reverse proxy, which re-writes the request before sending it to the application. Depending on the exact configuration, the host header in the rewritten request may be the internal hostname of the server, not the externally-reachable hostname of the reverse proxy.

Technically, the rewrite should result in the host header information being added to the X-Forwarded-Host header, but it's best to have a fall-back just in case.
