### ISSUE TITLE
mark columns/properties available/used for id/geom

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#76]
pls find a possibility to
* mark the used property for the id in each collection
* mark the geom property for each collection
* highlight the columns/properties which qualify for an id (unique values!) and can selected as id

**Comment by LukasGaebler** [comment]
Only columns which are primary keys in the database can be an id columns in the API right?

**Comment by hylkevds** [comment]
Or those with a "unique" constraint.
