### ISSUE TITLE
Landing page, list of collections problem

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#86]
The list of collections is filled with all collections even with those collections not holding a geometry, when the checkbox "Use" is clicked for a collection without geometry, the app hangs until the checkbox is "de-checked".
Expected behaviour:
collections without a valid geometry should not have a checkbox at all, instead there should be a text string: "no geom"
Is this possible?

**Comment by LukasGaebler** [comment]
yes possible and will be implemented
