### ISSUE TITLE
PostgreSQL connection not working

### ISSUE THREAD

**Issue by kgaeb** [DataCoveEU/API4INSPIRE#88]
the PG Connection is still not yet working - we need to find out together why this is not working
pls call me for a skype session!

**Comment by kgaeb** [comment]
tested with Chrome/FF/Edge - all the same!
but works on Linux Mint
any ideas?

**Comment by TobiasPressler** [comment]
The error was caused by an jdbc connection issue based on an to old library version. Fixed wit pull request #89
